# Generated by Django 3.2.4 on 2022-07-22 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0046_auto_20210921_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[449, 300], upload_to='services/'),
        ),
        migrations.CreateModel(
            name='UserMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subscriber')),
            ],
            options={
                'verbose_name_plural': 'Messages For User',
            },
        ),
    ]
