# Generated by Django 3.2.4 on 2022-08-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20220722_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('meal1', models.CharField(max_length=50)),
                ('meal2', models.CharField(max_length=50)),
                ('meal3', models.CharField(max_length=50)),
            ],
        ),
    ]
