# Generated by Django 3.2.4 on 2022-08-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_dietplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totals', models.CharField(max_length=50)),
                ('calories', models.CharField(max_length=50)),
                ('protien', models.CharField(max_length=50)),
                ('carbs', models.CharField(max_length=50)),
                ('fat', models.CharField(max_length=50)),
                ('dietplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dietplan')),
            ],
        ),
    ]
