# Generated by Django 3.2.4 on 2022-08-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='dietplan',
        ),
    ]
